Fixed Global search regressions
- Closes : #4438
- Fixes crash :
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:221)
	at app.lawnchair.search.algorithms.LawnchairLocalSearchAlgorithm.getResult(LawnchairLocalSearchAlgorithm.kt:179)
	at app.lawnchair.search.algorithms.LawnchairLocalSearchAlgorithm.access$getResult(LawnchairLocalSearchAlgorithm.kt:63)
	at app.lawnchair.search.algorithms.LawnchairLocalSearchAlgorithm$getResult$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bb7af8b, Dispatchers.Main]